import { test, expect } from '@playwright/test';
import { resolve } from 'node:path';
import { homedir } from 'node:os';
import { dismissGuide, samplePresent, sampleSkipReason } from './sample';

test('paths stay hidden while copies keep full paths, folder buttons work and recipient changes persist', async ({ page, context }) => {
  test.skip(!samplePresent, sampleSkipReason); await context.grantPermissions(['clipboard-read', 'clipboard-write']);
  await page.goto('/'); await dismissGuide(page);
  let finishLoading!: () => void;
  const loading = new Promise<void>(resolve => { finishLoading = resolve; });
  const layersUrl = (url: URL) => url.pathname === '/__studio/projects/sample-miko-qipao/built/layers.json';
  await page.route(layersUrl, async route => { await loading; await route.continue(); }, { times: 1 });
  const opening = page.waitForRequest(request => layersUrl(new URL(request.url())));
  await page.locator('.open-menu > summary').click(); await page.getByTestId('project-sample-miko-qipao').click();
  await opening;
  // Checking Mouth before the project finishes loading must survive the load.
  const mouth = page.getByTestId('variants-panel').getByRole('checkbox', { name: 'Mouth', exact: true });
  await mouth.check();
  finishLoading();
  const location = page.getByTestId('project-location');
  await expect(location.locator('strong')).toHaveText('Sample project');
  await expect(page.getByTestId('preview-status')).toHaveAttribute('data-state', 'ready');
  await expect(mouth).toBeChecked();
  const card = page.getByTestId('ask-agent-variants');
  await expect(card.locator('.root-path')).toHaveCount(0);
  await expect(location.locator('.project-path')).toHaveCount(0);
  await expect(location).not.toContainText('~/'); await expect(location).not.toContainText('samples/miko-qipao');
  await location.getByRole('button', { name: 'Copy path', exact: true }).click();
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(resolve('samples/miko-qipao'));
  const copyFolder = card.getByRole('button', { name: 'Copy folder path', exact: true });
  await copyFolder.click(); expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(resolve('.'));
  await expect(card.locator('.agent-folder-actions .copy-button')).toHaveText('✓ Copied');
  let revealed = false;
  await page.route('**/__studio/reveal', route => { revealed = true; return route.fulfill({ contentType: 'application/json', body: '{}' }); });
  await card.getByRole('button', { name: 'Open folder', exact: true }).click(); await expect.poll(() => revealed).toBe(true);
  const leaked = await page.locator('main').evaluate((main, home) => {
    const text = (main as HTMLElement).innerText, attributes = [...main.querySelectorAll('*')].flatMap(element => [...element.attributes].map(attr => attr.value));
    return [text, ...attributes].filter(value => value.includes(home));
  }, homedir()); expect(leaked).toEqual([]);
  const visiblePaths = await page.locator('[data-testid=project-location], .agent-folder-actions').evaluateAll(elements => elements.flatMap(element => [element.textContent ?? '', ...[element, ...element.querySelectorAll('*')].flatMap(child => [...child.attributes].map(attr => attr.value))]).filter(value => value.includes('~/') || value.includes('samples/miko-qipao')));
  expect(visiblePaths).toEqual([]);
  await card.getByRole('button', { name: 'Copy message', exact: true }).click();
  const codex = await page.evaluate(() => navigator.clipboard.readText());
  for (const word of ['imagegen', 'source.png', 'variants/', 'build-sprites', 'render-poses', 'already consented', 'Do not use other external services']) expect(codex).toContain(word);
  await expect(card.getByText('Images will be sent to Codex image generation.', { exact: true })).toBeVisible();
  await card.getByRole('button', { name: 'Claude Code', exact: true }).click();
  await expect(card.getByRole('button', { name: 'Claude Code', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(card.locator('.agent-disclosure')).toHaveCount(0);
  await expect(card.getByRole('textbox')).toContainText('then stop'); await expect(card.getByRole('textbox')).toContainText('Do not generate or send images');
  await page.reload(); await expect(page.getByTestId('preview-status')).toHaveAttribute('data-state', 'ready');
  await page.getByTestId('variants-panel').getByRole('checkbox', { name: 'Mouth', exact: true }).check();
  await expect(card.getByRole('button', { name: 'Claude Code', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: '日本語', exact: true }).click();
  await expect(card.getByRole('textbox')).toContainText('そこで止まってください'); await expect(card.locator('.agent-instruction')).toContainText('Claude Code');
  await card.getByRole('button', { name: 'Codex', exact: true }).click();
  await expect(card.getByText('画像は Codex の画像生成に送られます', { exact: true })).toBeVisible();
  await expect(card.getByRole('textbox')).toContainText('ユーザーは Codex の画像生成の利用に同意済み');
  await expect(card.locator('.agent-instruction')).toHaveText('このリポジトリのフォルダで Codex を開いて、次の文章を貼ってください。');
  await card.getByRole('button', { name: 'フォルダのパスをコピー', exact: true }).click();
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(resolve('.'));
  await expect(card.locator('.agent-folder-actions .copy-button')).toHaveText('✓ コピーしました');
  await expect(card.getByRole('button', { name: 'フォルダを開く', exact: true })).toBeVisible();
  await page.route('**/__studio/reveal', route => route.fulfill({ status: 500, contentType: 'application/json', body: '{}' }));
  await card.getByRole('button', { name: 'フォルダを開く', exact: true }).click(); await expect(card.getByRole('alert')).toBeVisible();
});
test('blocked preference storage still allows recipient and wheel mode changes', async ({ page }) => {
  test.skip(!samplePresent, sampleSkipReason);
  await page.addInitScript(() => { Object.defineProperty(window, 'localStorage', { get() { throw new DOMException('Blocked', 'SecurityError'); } }); });
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/'); await dismissGuide(page);
  await page.getByTestId('variants-panel').getByRole('checkbox', { name: 'Mouth', exact: true }).check();
  await page.getByTestId('ask-agent-variants').getByRole('button', { name: 'Claude Code', exact: true }).click();
  await expect(page.getByTestId('ask-agent-variants').getByRole('textbox')).toContainText('Claude Code cannot generate images');
  await page.getByRole('combobox', { name: 'Mouse wheel', exact: true }).selectOption('pan');
  await expect(page.getByRole('combobox', { name: 'Mouse wheel', exact: true })).toHaveValue('pan'); expect(errors).toEqual([]);
});
